### ISSUE TITLE
[Question] How does the S3 package share the credentials between client and server?

### ISSUE THREAD

**Issue by luckyvs1** [Lepozepo/S3#162]
I was playing around with the AWS SDK in MeteorJS and had some issues accessing config credentials in the client if I stored the credentials in the server. But when I used your package it makes it possible to have the config setup in the server side and have client side upload and delete function possible.

Just looking into working with AWS SDK and any help would be appreciated in this regard.

**Comment by Lepozepo** [comment]
There isn't really a good way of interfacing with AWS SDK on the client (because it's not meant to be on the client, if it was you'd expose your private keys). AWS SDK assumes your infrastructure has server-side rendering (which Meteor does not have out of the box) so that you can build forms with the required params on the server and pass them directly to the client. This package uses `Meteor.methods` to interface with server functions and get info like [this](https://github.com/Lepozepo/S3/blob/master/client/functions.coffee#L164) which in turn produces a virtual form to make the upload work.

**Comment by luckyvs1** [comment]
Much appreciated and thank you for the insight
